# Generated by Django 4.1.1 on 2022-09-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter subject name', max_length=100, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject ',
                'verbose_name_plural': 'Subjects ',
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter teacher name', max_length=100, verbose_name='Name')),
                ('one_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(help_text='Enter phone number', max_length=900, verbose_name='Phone number')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
            options={
                'verbose_name': 'Teacher ',
                'verbose_name_plural': 'Teachers ',
                'db_table': 'Teacher',
            },
        ),
    ]
