# Generated by Django 4.1.1 on 2022-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlokTestlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_kodi', models.CharField(max_length=600, verbose_name='Test Code')),
                ('fan_nomi', models.CharField(max_length=700, verbose_name='Subject')),
                ('oquvchi', models.CharField(max_length=600)),
                ('tel', models.CharField(max_length=700)),
                ('fan1', models.IntegerField()),
                ('fan2', models.IntegerField()),
                ('fan3', models.IntegerField()),
                ('fan4', models.IntegerField()),
                ('fan5', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FanTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_kodi', models.CharField(max_length=600, verbose_name='Test Code')),
                ('fan_nomi', models.CharField(max_length=700, verbose_name='Subject')),
                ('oquvchi', models.CharField(max_length=600)),
                ('tel', models.CharField(max_length=700)),
                ('test_soni', models.IntegerField()),
                ('fan', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
