# Generated by Django 4.1.1 on 2022-10-05 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_bloktestlar_options_alter_fantest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='fan_nomi',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='oquvchi',
            new_name='first_block',
        ),
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='fan3',
            new_name='matematika',
        ),
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='fan4',
            new_name='ona_tili',
        ),
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='tel',
            new_name='second_block',
        ),
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='fan5',
            new_name='tarix',
        ),
        migrations.RenameField(
            model_name='bloktestlar',
            old_name='test_kodi',
            new_name='week_code',
        ),
        migrations.RemoveField(
            model_name='bloktestlar',
            name='sana',
        ),
        migrations.AddField(
            model_name='bloktestlar',
            name='ball',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloktestlar',
            name='global_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloktestlar',
            name='global_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloktestlar',
            name='image_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloktestlar',
            name='local_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloktestlar',
            name='sms_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
