# Generated by Django 4.1.1 on 2022-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=1000, verbose_name='Name')),
                ('region', models.CharField(choices=[('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ("farg'ona", "Farg'ona"), ('jizzax', 'Jizzax'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ("qoraqalpog'iston", "Qoraqalpog'iston"), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('toshkent', 'Toshkent')], default='qashqadaryo', help_text='Choose region', max_length=6000, verbose_name='Region')),
                ('address', models.CharField(help_text='Enter address', max_length=9000, verbose_name='Address')),
                ('phone', models.CharField(help_text='Enter phone number', max_length=900, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Parent ',
                'verbose_name_plural': 'Parents ',
                'db_table': 'Parent',
            },
        ),
    ]
