# Generated by Django 4.1.1 on 2022-09-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='region',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Xorazm', 'Xorazm'), ('Toshkent', 'Toshkent')], default='qashqadaryo', help_text='Choose region', max_length=6000, verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=1000, verbose_name='Name')),
                ('address', models.CharField(help_text='Enter address', max_length=9000, verbose_name='Address')),
                ('image', models.ImageField(help_text='Upload image', upload_to='student-image', verbose_name='Image')),
                ('phone', models.CharField(help_text='Enter phone number', max_length=900, verbose_name='Phone number')),
                ('one_id', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.parent')),
            ],
        ),
    ]
