# Generated by Django 4.1.1 on 2022-09-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_parent_region_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student ', 'verbose_name_plural': 'Students '},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
