# Generated by Django 4.1.1 on 2022-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=100, verbose_name='Name')),
                ('phone', models.CharField(help_text='Enter phone number', max_length=900, verbose_name='Phone number')),
                ('about', models.TextField(help_text='Enter about tuitor', verbose_name='About tuitor')),
            ],
            options={
                'verbose_name': 'Tuitor ',
                'verbose_name_plural': 'Tuitors ',
                'db_table': 'Tuitor',
            },
        ),
    ]
